.PHONY: clean All

All:
	@echo "----------Building project:[ inputOuput - Debug ]----------"
	@cd "inputOuput" && "$(MAKE)" -f  "inputOuput.mk"
clean:
	@echo "----------Cleaning project:[ inputOuput - Debug ]----------"
	@cd "inputOuput" && "$(MAKE)" -f  "inputOuput.mk" clean
