.PHONY: clean All

All:
	@echo "----------Building project:[ PEC4 - Debug ]----------"
	@cd "PEC4" && "$(MAKE)" -f  "PEC4.mk"
clean:
	@echo "----------Cleaning project:[ PEC4 - Debug ]----------"
	@cd "PEC4" && "$(MAKE)" -f  "PEC4.mk" clean
