.PHONY: clean All

All:
	@echo "----------Building project:[ UOCoworking2 - Debug ]----------"
	@cd "UOCoworking2" && "$(MAKE)" -f  "UOCoworking2.mk"
clean:
	@echo "----------Cleaning project:[ UOCoworking2 - Debug ]----------"
	@cd "UOCoworking2" && "$(MAKE)" -f  "UOCoworking2.mk" clean
