.PHONY: clean All

All:
	@echo "----------Building project:[ UOCCoworking - Test ]----------"
	@cd "UOCCoworking" && "$(MAKE)" -f  "UOCCoworking.mk"
clean:
	@echo "----------Cleaning project:[ UOCCoworking - Test ]----------"
	@cd "UOCCoworking" && "$(MAKE)" -f  "UOCCoworking.mk" clean
