.PHONY: clean All

All:
	@echo "----------Building project:[ Pec3 - Debug ]----------"
	@cd "Pec3" && "$(MAKE)" -f  "Pec3.mk"
clean:
	@echo "----------Cleaning project:[ Pec3 - Debug ]----------"
	@cd "Pec3" && "$(MAKE)" -f  "Pec3.mk" clean
