.PHONY: clean All

All:
	@echo "----------Building project:[ PEC6 - Debug ]----------"
	@cd "PEC6" && "$(MAKE)" -f  "PEC6.mk"
clean:
	@echo "----------Cleaning project:[ PEC6 - Debug ]----------"
	@cd "PEC6" && "$(MAKE)" -f  "PEC6.mk" clean
