.PHONY: clean All

All:
	@echo "----------Building project:[ PEC5 - Debug ]----------"
	@cd "PEC5" && "$(MAKE)" -f  "PEC5.mk"
clean:
	@echo "----------Cleaning project:[ PEC5 - Debug ]----------"
	@cd "PEC5" && "$(MAKE)" -f  "PEC5.mk" clean
